### ISSUE TITLE
FATAL dbench-bench: Failed to run tbench

### ISSUE THREAD

**Issue by chenliangfei** [gormanm/mmtests#19]
[root@localhost log]# /home/mmtests-master/run-mmtests.sh -c /home/mmtests-master/configs/config-network-tbench base_core_tbench
Building shellpacks
Package must be a directory

Using default SHELLPACK_DATA
Installing test tbench4
dbench installed only as requested.
tbench4 fine
Starting test tbench4
Started monitor proc-vmstat gzip pid 18862
Started monitor mpstat gzip pid 18869
Waiting on pidfile /tmp/monitor-2.17681.pid to be created
Started monitor vmstat latency pid 18880,18881

Stopping tbench_srv
tbench_srv: no process found
tbench run 1
Starting tbench_srv
FATAL dbench-bench: Failed to run tbench
FATAL: tbench4 returned failure, unable to continue
Shutting down monitor: 18862
Shutting down monitor: 18869
Shutting down monitor: 18880
Shutting down monitor: 18881
test exit :: tbench4 255
Cleaning up
[root@localhost log]#
[root@localhost log]# which tbench_srv
/usr/bin/tbench_srv
[root@localhost log]# which tbench
/usr/bin/tbench
[root@localhost log]#

What can I do if the preceding error is reported?

**Comment by gormanm** [comment]
This issue is ancient and I missed it as notifications were not enabled. It appears to be working at the moment so closing. Reopen if necessary. Thanks.
