### ISSUE TITLE
set_mmtests_numactl wasn't invoked

### ISSUE THREAD

**Issue by ZhangYet** [gormanm/mmtests#21]
Found that set_mmtests_numactl wasn't invoked before so that `export MMTESTS_NUMA_POLICY="fullbind_single_instance_cpu"` didn't work when testing the impact of NUMA policies on redis. So I made some changes.

https://github.com/gormanm/mmtests/pull/20

But I found `MMTESTS_NUMACTL` in some bench like `/shellpack_src/src/iozone/iozone-bench`, and I don't know why.

**Comment by gormanm** [comment]
NUMA policies and how they are applied needs a rethink. It's somewhat benchmark specific how the binding should be done so it needs to be divided into generic and benchmark-specific configuration options. As bindings are not often used, it's on the backburner to address in a sensible fashion.
