### ISSUE TITLE
FATAL bonniepp-install: bonniepp-install: Could not download /bonnie++-1.98.tgz

### ISSUE THREAD

**Issue by bwgartner** [gormanm/mmtests#22]
This version does not yet appear to be available on https://www.coker.com.au/bonnie++/ to be used by
- config-io-bonniepp-dir-async
- config-io-bonniepp-file-async

**Comment by gormanm** [comment]
This may have been a transient error because when I try this, I get the following output;

bonniepp-install: Fetching from internet https://www.coker.com.au/bonnie++/bonnie++-1.98.tgz
/home/mel/git-priva 100%[===================>]  97.99K  --.-KB/s    in 0.1s

The version is mentioned under "New experimental releases, will soon be released as 2.0x at which time 1.0x releases will be deprecated" and a link is available on the page https://doc.coker.com.au/projects/bonnie/.

Closing for now but reopen if necessary.

**Comment by bwgartner** [comment]
> This may have been a transient error because when I try this, I get the following output;

Could still be the case for me, as the source provider webpage does now show this version

> bonniepp-install: Fetching from internet https://www.coker.com.au/bonnie++/bonnie++-1.98.tgz /home/mel/git-priva 100%[===================>] 97.99K --.-KB/s in 0.1s

however, still not working for me yet

# sh -x ./run-mmtests.sh --no-monitor --config configs/config-io-bonniepp-file-async fix.config-io-bonniepp-file-async
+ set +x
Refreshing service 'SMT-http_smt_stable_suse_lab'.
Loading repository data...
Reading installed packages...
'hwloc' not found in package names. Trying capabilities.
No provider of 'hwloc' found.
Refreshing service 'SMT-http_smt_stable_suse_lab'.
Loading repository data...
Reading installed packages...
'hwloc' not found in package names. Trying capabilities.
No provider of 'hwloc' found.
WARNING: Failed to cleanly install package hwloc for distro suse
Installed hwloc
Refreshing service 'SMT-http_smt_stable_suse_lab'.
Loading repository data...
Reading installed packages...
'perl-Time-HiRes' not found in package names. Trying capabilities.
'perl' providing 'perl-Time-HiRes' is already installed.
Resolving package dependencies...

Nothing to do.
Installed perl-Time-HiRes
Building shellpacks

Using default SHELLPACK_DATA
modprobe: FATAL: Module msr not found in directory /lib/modules/4.12.14-120-default
modprobe: FATAL: Module msr not found in directory /lib/modules/4.12.14-120-default
Installing test bonniepp
pid 21076's current affinity list: 0-3
pid 21076's new affinity list: 0-3
pid 21076's current affinity list: 0-3
pid 21076's new affinity list: 0-3
bonniepp-install: Fetching from mirror http://mcp/mmtests-mirror/bonnie/bonnie++-1.98.tgz
bonniepp-install: Fetching from internet https://www.coker.com.au/bonnie++/bonnie++-1.98.tgz
bonniepp-install: Fetching from alt internet /bonnie++-1.98.tgz
FATAL bonniepp-install: bonniepp-install: Could not download /bonnie++-1.98.tgz
FATAL bonniepp-bench: bonniepp install script returned error
FATAL: bonniepp returned failure, unable to continue
FATAL: Installation step failed for bonniepp

> The version is mentioned under "New experimental releases, will soon be released as 2.0x at which time 1.0x releases will be deprecated" and a link is available on the page https://doc.coker.com.au/projects/bonnie/.
> 
> Closing for now but reopen if necessary.

And possibly another cause

# wget https://www.coker.com.au/bonnie++/bonnie++-1.98.tgz
--2022-07-12 18:37:33--  https://www.coker.com.au/bonnie++/bonnie++-1.98.tgz
Resolving www.coker.com.au (www.coker.com.au)... 144.76.223.240, 2a01:4f8:201:1e6::d0d0:c0de
Connecting to www.coker.com.au (www.coker.com.au)|144.76.223.240|:443... connected.
ERROR: cannot verify www.coker.com.au's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to www.coker.com.au insecurely, use `--no-check-certificate'.

yet if one uses the wget --no-check-certificate via https (or even http) URl approach, the content can be downloaded (but that doesn't address the run-mmtests.sh invocation)
