### ISSUE TITLE
$WEBROOT url is not accessible 

### ISSUE THREAD

**Issue by srikanth007m** [gormanm/mmtests#3]
Hi, 

I am trying filelockperf and it failed to fetch the source form $WEBROOT and this is assigned http://mcp/mmtests-mirror to $WEBROOT under shellpacks/common-config.sh. This webroot URL is not reachable to download the source even for the tests. Can i know what is the working URL to update ?

**Comment by athira-rajeev** [comment]
Hi, 
WEBROOT still points to wrong location. "http://mcp/mmtests-mirror" . May I know what is the expected mirror location ?

**Comment by CentUser** [comment]
download the packages elsewhere, then start a new http server, and then config the WEBROOT to your server... @

**Comment by edlgg** [comment]
@CentUser Im running into the same problem. Can you provide any orientation on how to download the packages elsewhere. Also, do you know if it is possible to store them locally to then run the tests. Thanks.

**Comment by gormanm** [comment]
Mirrors are configured locally. If a mirror is not available, the packages are downloaded from upstream if possible. Sometimes the upstream links go stale (which is partially why mirroring was implemented in the first place)

**Comment by CentUser** [comment]
> @CentUser Im running into the same problem. Can you provide any orientation on how to download the packages elsewhere. Also, do you know if it is possible to store them locally to then run the tests. Thanks.

Sorry for the delayed reply.
You can download the needed packages to one dir, and then using httpd or python -m SimpleHTTPServer 80 as an temporary server, and then configure mmtests mirror to the localhost:80 . That would solve the problem.
