### ISSUE TITLE
there is no shellpacks/shellpack-bench-dbench4 scripts

### ISSUE THREAD

**Issue by CentUser** [gormanm/mmtests#7]
https://github.com/gormanm/mmtests/blob/e943c083f32dff836af62a36e57890a11f1b1bc4/configs/config-global-dhp__io-dbench4-async#L21

**Comment by CentUser** [comment]
So, there is a grep Error in run-mmtests.sh line 606, you cannot find a file named shellpacks/shellpack-bench-dbench4.

**Comment by gormanm** [comment]
I don't think this is relevant any more as shellpacks are now always created unconditionally and dbench appears to be working.
