### ISSUE TITLE
Where can I download the relevant files for the tests?

### ISSUE THREAD

**Issue by edlgg** [gormanm/mmtests#8]
According to [this](https://github.com/gormanm/mmtests/issues/3) issue I should download the necessary packages to test elsewhere. I´ve been looking around but I cant find a mirror. What can I do? Thanks.

**Comment by gormanm** [comment]
Tests are downloaded from upstream where applicable. The links may go stale in which case the location can be updated in shellpack_src/src/TESTNAME/TESTNAME-install
