### ISSUE TITLE
Running into error while trying to launch run-kvm.sh on Aarch64.

### ISSUE THREAD

**Issue by Amar-Bharamshetti** [gormanm/mmtests#9]
Hi, 

I have installed all required packages on Centos 8 which is running on an Aarch64 server. When I am trying launch 'run-kvm.sh', I am running into below error.

Log snippet :

[root@localhost mmtests]# ./run-kvm.sh
Last metadata expiration check: 0:53:15 ago on Sun 05 Apr 2020 05:14:57 PM IST.
No match for argument: pssh
Error: Unable to find a match
Failed to install package pssh for distro redhat at /root/mmtests/bin/install-depends line 243.
Booting the VM(s)
Starting marvin-mmtests
error: failed to get domain 'marvin-mmtests'
error: Domain not found: no domain with matching name 'marvin-mmtests'

Console available via "virsh console marvin-mmtests", waiting on IP
error: failed to get domain 'marvin-mmtests'
error: Domain not found: no domain with matching name 'marvin-mmtests'

Any idea what the issue is and how to fix it ?

Thanks a lot for your support.

Best Regards,
Amar

**Comment by gormanm** [comment]
I've never tried making this work on centos or aarch64. However, a minimum requirement is the existence of a marvin-mmtests domain. MMTests does not handle that. On the test grid I maintain, the installation of a virtual test machine is handled by grid management software. The package dependency names are based on opensuse so in many cases, a mapping is needed in bin/install-depends too make an opensuse package name to the centos equivalent.
